project_id = "lozeazpliiesvpwusmgu"

[functions.check-subscription]
verify_jwt = false

[functions.verify-subscription]
verify_jwt = false

[functions.upload-to-ipfs]
verify_jwt = false

[functions.get-clerk-publishable-key]
verify_jwt = false

[functions.sync-crossmint-wallet]
verify_jwt = false
